# What is NumPy?

#### NumPy is a Python library usd for working with arrays.
#### It also has functions for working in domain of linear algebra, fourier transform, and matrices.
#### NumPy stands for Numerical Python.

# Why Use NumPy?

#### In Python we have lists that serve the purpose of arrays, but they are slow to process.
#### NumPy aims to provide an array object that is up to 50x faster than traditional lists.
#### The array object in NumPy is called 'ndarray', it provides a lot of supporting functions that make working with 'ndarray' very easy.
#### Arrays are very frequently used in data science, where speed and resources are very important.
#### Data science: It is branch of computer science where we study how to store, use and analyze data for deriving information from it.

# Why is NumPy Faster than Lists?

#### NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
#### This behavior is called locality of references in computer science.
#### This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# Import NumPy

#### Once NumPy is installed, import it in your applications by adding the 'import' keyword.

In [43]:
import numpy

#### Now NumPy is imported and ready to use.

## Example:

In [44]:
import numpy
arr = numpy.array([1,2,3,4])
print(arr)

[1 2 3 4]


# NumPy as np
#### NumPy is usually imported under the 'np' alias.
#### 'alias':In Python alias are an alternate name for referring to the same thing.
#### Create an alias with the 'as' keyword while importing.

In [45]:
import numpy as np

In [46]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


# Checking NumPy Version
#### The version string is stored under '_ _version_ _' attribute.

In [47]:
print(np.__version__)

1.21.2


# NumPy Creating Arrays

## Create a NumPy ndarray Object
#### NumPy is used to work with arrays.The array object in NumPy is called 'ndarray'.
#### We can create a NumPy 'ndarray' object by using the 'array()' function.

In [48]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### To create an 'ndarray', we can pass a list, tuple or any array-like object into the 'array()' method, and it will be converted into an array 'ndarray'

#### Use a tuple to create a NumPy array:

In [49]:
arr = np.array((1,2,3,4,5))
print('Create array by using tuple:',arr)

Create array by using tuple: [1 2 3 4 5]


#### Use a list to create a NumPy array:

In [50]:
arr = np.array([1,2,3,4,5])
print('Create array by using list:',arr)

Create array by using list: [1 2 3 4 5]


## Dimensions in Arrays
#### A dimensions in arrays is one level of array depth(nested array).
#### nested array: are arrays that have arrays as their elements.

### 0-D Arrays
#### 0-D arrays, or Scalars, are the elements in an array. Each value in an array is 0-D array.

In [51]:
arr = np.array(42)
print('print 0-D array:',arr)

print 0-D array: 42


### 1-D Arrays
#### An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [52]:
arr = np.array([1,2,3,4,5])
print('print 1-D array:',arr)

print 1-D array: [1 2 3 4 5]


### 2-D Arrays
#### An array that has 1-D arrays as its elements is called a 2-D array.

In [53]:
arr = np.array([[10,20,3,0],[50,20,30,40]])
print('print 2-D array:',arr)

print 2-D array: [[10 20  3  0]
 [50 20 30 40]]


### 3-D Arrays
#### An array that has 2-D arrays as its elements is called a 3-D array.

In [54]:
arr = np.array([[[10,20,3,0],[50,20,30,40],[1,2,3,4],[5,6,7,8]]])
print('print 3-D array:',arr)

print 3-D array: [[[10 20  3  0]
  [50 20 30 40]
  [ 1  2  3  4]
  [ 5  6  7  8]]]


## Check Number of Dimensions?

#### NumPy Arrays provides the 'ndim' attribute that returns an integer that tells us how many dimensions the array have.

In [55]:
a = np.array(42)
b = np.array([1,2,3,4])
c = np.array([[45,55,65,75],[10,20,30,40]])
d = np.array([[[10,20,30,40],[50,60,70,80],[90,100,101,102]]])
print('print a array:',a)
print('print b array:',b)
print('print c array:',c)
print('print d array:',d)
print('Dimension of a array:',a.ndim)
print('Dimension of b array:',b.ndim)
print('Dimension of c array:',c.ndim)
print('Dimension of d array:',d.ndim)

print a array: 42
print b array: [1 2 3 4]
print c array: [[45 55 65 75]
 [10 20 30 40]]
print d array: [[[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 101 102]]]
Dimension of a array: 0
Dimension of b array: 1
Dimension of c array: 2
Dimension of d array: 3


## Check Number of Dimensions?
#### NumPy Arrays provides the 'ndim' attribute that returns an integer that tells us how many dimensions the array have.

In [56]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3])
c = np.array([[10,20,30],[80,95,68]])
d = np. array([[[5,15,25,35],[9,18,27,36],[11,22,33,44]]])
print('Print Array a:',a)
print('Print Array b:',b)
print('Print Array c:',c)
print('Print Array d:',d)
print('Dimension of Array a is:',a.ndim)
print('Dimension of Array b is:',b.ndim)
print('Dimension of Array c is:',c.ndim)
print('Dimension of Array d is:',d.ndim)

Print Array a: 42
Print Array b: [1 2 3]
Print Array c: [[10 20 30]
 [80 95 68]]
Print Array d: [[[ 5 15 25 35]
  [ 9 18 27 36]
  [11 22 33 44]]]
Dimension of Array a is: 0
Dimension of Array b is: 1
Dimension of Array c is: 2
Dimension of Array d is: 3


### Higher Dimensional  Arrays
#### An Array can have any number of dimensions.
#### When the array is created, you can define the number of dimensions by using the 'ndim' argument.

In [57]:
arr = np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('Number of dimensions:',arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of dimensions: 5


### ndarray.size
#### The Total number of elements of the array. This is equal to the product of the elements of shape.

In [58]:
a = np.array(42)
b = np.array([1,2,3])
c = np.array([[10,20,30],[80,95,68]])
d = np. array([[[5,15,25,35],[9,18,27,36],[11,22,33,44]]])
print('size of array a:',a.size)
print('size of array b:',b.size)
print('size of array c:',c.size)
print('size of array d:',d.size)

size of array a: 1
size of array b: 3
size of array c: 6
size of array d: 12


### len(ndarray)
#### It also gives the total elements of the array.

In [59]:
#a = np.array(42)
b = np.array([1,2,3])
c = np.array([[10,20,30],[80,95,68]])
d = np. array([[[5,15,25,35],[9,18,27,36],[11,22,33,44]]])
#print('size of array a:',len(a))
print('size of array b:',len(b))
print('size of array c:',len(c))
print('size of array d:',len(d))

size of array b: 3
size of array c: 2
size of array d: 1


### ndarray.shape
#### It gives the dimensions of array. This is tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, 'shape' will be(n,m). The length of the shape tuple is therefore the number of axes,'ndim'.

In [60]:
a = np.array(42)
b = np.array([1,2,3])
c = np.array([[10,20,30],[80,95,68]])
d = np. array([[[5,15,25,35],[9,18,27,36],[11,22,33,44]]])
print('Shape of array a is:',a.shape)
print('Shape of array b is:',b.shape)
print('Shape of array c is:',c.shape)
print('Shape of array d is:',d.shape)

Shape of array a is: ()
Shape of array b is: (3,)
Shape of array c is: (2, 3)
Shape of array d is: (1, 3, 4)


### ndarray.dtype
#### An object describing the type of the elements in the array. One can create or specify 'dtype's' using standard Python types. Additionally NumPy provides types of its own.
#### numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [61]:
a = np.array(42)
b = np.array([1,2,3])
c = np.array([[10,20,30],[80,95,68]])
d = np. array([[[5,15,25,35],[9,18,27,36],[11,22,33,44]]])
print('dtype of array a is:',a.dtype)
print('dtype of array b is:',b.dtype)
print('dtype of array c is:',c.dtype)
print('dtype of array d is:',d.dtype)

dtype of array a is: int32
dtype of array b is: int32
dtype of array c is: int32
dtype of array d is: int32


## How to create array using built-in numpy functions?

#### equivalent to range function in python
#### arange([start,] stop[, step,], dtype=None)
#### Return evenly spaced values within a given interval.
#### To create sequence of numbers, NumPy provides the 'arange' function which is analagous to the Python buit-in 'range', but returns an array.

### np.arange(n)        #0 to n-1

In [62]:
a = np.arange(15)
print('a Array is:',a)

a Array is: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [63]:
b = np.arange(5)
print('b Array is:',b)

b Array is: [0 1 2 3 4]


#### Start and Stop

In [64]:
a = np.arange(1,15)
print('a Array is:',a)

a Array is: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### Stepping by 2 means will skip 1 element

In [65]:
a = np.arange(1,15,2)
print('a Array is:',a)

a Array is: [ 1  3  5  7  9 11 13]


In [66]:
a = np.arange(1,15,-1)
print('a Array is:',a)

a Array is: []


In [67]:
a = np.arange(15,1,-1)
print('a Array is:',a)

a Array is: [15 14 13 12 11 10  9  8  7  6  5  4  3  2]


In [68]:
a1 = np.arange(0,2,0.3) # it returns float arguments
print('a1 Array is:',a1)

a1 Array is: [0.  0.3 0.6 0.9 1.2 1.5 1.8]


### np.linspace()
#### When 'arange' is used with floating point argumnets, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function 'linspace' that receives as an argument the number of elements that we want, instead of step:
#### In linspace() method stop is inclusive.

In [69]:
a2 = np.linspace(1,15)
print('a2 Array is:',a2)

a2 Array is: [ 1.          1.28571429  1.57142857  1.85714286  2.14285714  2.42857143
  2.71428571  3.          3.28571429  3.57142857  3.85714286  4.14285714
  4.42857143  4.71428571  5.          5.28571429  5.57142857  5.85714286
  6.14285714  6.42857143  6.71428571  7.          7.28571429  7.57142857
  7.85714286  8.14285714  8.42857143  8.71428571  9.          9.28571429
  9.57142857  9.85714286 10.14285714 10.42857143 10.71428571 11.
 11.28571429 11.57142857 11.85714286 12.14285714 12.42857143 12.71428571
 13.         13.28571429 13.57142857 13.85714286 14.14285714 14.42857143
 14.71428571 15.        ]


In [70]:
a2 = np.linspace(2,10)
print('a2 array is:',a2)

a2 array is: [ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]


In [71]:
a2 = np.linspace(2,10,5)
print('a2 array is:',a2)

a2 array is: [ 2.  4.  6.  8. 10.]


In [72]:
a2 = np.linspace(2,10,15)
print('a2 array is:',a2)

a2 array is: [ 2.          2.57142857  3.14285714  3.71428571  4.28571429  4.85714286
  5.42857143  6.          6.57142857  7.14285714  7.71428571  8.28571429
  8.85714286  9.42857143 10.        ]


In [73]:
a2 = np.linspace(2,10,150)
print('a2 array is:',a2)

a2 array is: [ 2.          2.05369128  2.10738255  2.16107383  2.2147651   2.26845638
  2.32214765  2.37583893  2.4295302   2.48322148  2.53691275  2.59060403
  2.6442953   2.69798658  2.75167785  2.80536913  2.8590604   2.91275168
  2.96644295  3.02013423  3.0738255   3.12751678  3.18120805  3.23489933
  3.2885906   3.34228188  3.39597315  3.44966443  3.5033557   3.55704698
  3.61073826  3.66442953  3.71812081  3.77181208  3.82550336  3.87919463
  3.93288591  3.98657718  4.04026846  4.09395973  4.14765101  4.20134228
  4.25503356  4.30872483  4.36241611  4.41610738  4.46979866  4.52348993
  4.57718121  4.63087248  4.68456376  4.73825503  4.79194631  4.84563758
  4.89932886  4.95302013  5.00671141  5.06040268  5.11409396  5.16778523
  5.22147651  5.27516779  5.32885906  5.38255034  5.43624161  5.48993289
  5.54362416  5.59731544  5.65100671  5.70469799  5.75838926  5.81208054
  5.86577181  5.91946309  5.97315436  6.02684564  6.08053691  6.13422819
  6.18791946  6.24161074  6.29530201  

In [74]:
a2 = np.linspace(2,10,10)
print('a2 array is:',a2)

a2 array is: [ 2.          2.88888889  3.77777778  4.66666667  5.55555556  6.44444444
  7.33333333  8.22222222  9.11111111 10.        ]


### stop we want to make exclusive

In [75]:
arr = np.linspace(2,10,10,endpoint=False)
print('arr is:',arr)

arr is: [2.  2.8 3.6 4.4 5.2 6.  6.8 7.6 8.4 9.2]


### To see the stepping between the numbers use retstep

In [76]:
arr =np.linspace(2,10,10,endpoint=False,retstep=True)
print('arr is:',arr)

arr is: (array([2. , 2.8, 3.6, 4.4, 5.2, 6. , 6.8, 7.6, 8.4, 9.2]), 0.8)


In [77]:
arr = np.linspace(6,-6,13)
print('arr is:',arr)

arr is: [ 6.  5.  4.  3.  2.  1.  0. -1. -2. -3. -4. -5. -6.]


In [78]:
arr = np.linspace(-6,6,13)
print('arr is:',arr)

arr is: [-6. -5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.  6.]


In [79]:
arr = np.arange(-6,7)
print('arr is:',arr)

arr is: [-6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6]


In [80]:
list(range(-6,7))

[-6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6]

### np.zeros()
#### The function 'zeros' creates an array full of zeros.

In [81]:
a3 = np.zeros(5)
print('a3:',a3)

a3: [0. 0. 0. 0. 0.]


In [82]:
print('shape of a3:',a3.shape)

shape of a3: (5,)


In [83]:
a4 = np.zeros((3,4))
print(a4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [84]:
a5 = np.zeros((4,4))
print(a5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### np.ones()
#### The function 'ones' creates an array full of ones.

In [85]:
a = np.ones(5)
print('a array is:',a)

a array is: [1. 1. 1. 1. 1.]


In [86]:
a = np.ones((4,4))
print('a Array is:',a)

a Array is: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### np.empty()
#### The function 'empty' creates an array whose initial content is random and depends on the created array is 'float64'.

In [87]:
a = np.empty((3,4))
print('a Array is:',a)

a Array is: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [88]:
import numpy as np
a = np.empty([3,3])
print("a:",a)

a: [[3.60739285e-313 4.03179200e-313 2.54639495e-313]
 [8.48798317e-314 2.97079411e-313 2.12199579e-313]
 [2.54639495e-313 6.36598738e-314 2.97079411e-313]]


### np.eye()
####  i want diagonal elemts 1 and non diagonal 0's

In [89]:
a = np.eye((4))
print('a Array is:',a)

a Array is: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### its same like identity matrix==same no of rows and columns

In [90]:
a = np.eye(4,3)
print('a:',a)

a: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


### np.identity()

#### Return the identity array.

In [91]:
a = np.identity(5)
print('a:',a)

a: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [92]:
a = np.identity(7)
print('a:',a)

a: [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


### np.diagonal()
#### It returns the diagonal elements in the array

In [93]:
print(a.diagonal())

[1. 1. 1. 1. 1. 1. 1.]


## NumPy Array Indexing

### Access Array Elements
#### Array indexing is the same as accessing an array element.
#### You can access an array element by referring to its index number.
#### The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [94]:
arr = np.array([1,2,3,4])
print('arr is:',arr)
print('Access second element in array:',arr[1])

arr is: [1 2 3 4]
Access second element in array: 2


#### Get third and fourth elements from the following array and add them.

In [95]:
arr = np.array([1,2,3,4,5])
print('arr is:',arr)
print(arr[2] + arr[3])

arr is: [1 2 3 4 5]
7


### Access 2-D Arrays
#### To access elements from 2-D arrays we can use comma seperated integers representing the dimension and the index of the element.

In [96]:
arr = np.array([[1,2,34,5],[10,20,35,45]])
print('2nd element on 1st dim:',arr[0,1])

2nd element on 1st dim: 2


In [97]:
print('4th element on 2nd dim:',arr[1,3])

4th element on 2nd dim: 45


### Access 3-D Arrays
#### To access elements from 3-D arrays we can use comma seperated integers representing the dimensions and the index of the element.

In [98]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print('Third element of the second array of the first array is:',arr[0,1,2])

Third element of the second array of the first array is: 6


### Negative Indexing

In [99]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


### np.full()
#### numpy.ndarray.fill() method is used to fill the numpy array with scalar value. 
#### Syntax: ndarray.fill(fill_value)
#### Parameters:
#### value: All elements of a will be assigned this value.

In [100]:
arr = np.arange(5)
print('arr:',arr)
arr.fill(0)
print('updated_arr:',arr)

arr: [0 1 2 3 4]
updated_arr: [0 0 0 0 0]


### np.full()
#### numpy.full(shape, fill_value, dtype = None, order = 'C'): return a new array with the same shape and type as a given array filled with a fill_value.
#### Parameter:
    #shape : Number of rows
    #order : C_contiguous or F_contiguous
    #dtype : [optional, float(by_default)] Data
    #fill_value : [bool, optional] value to fill in the array.

In [102]:
arr = np.full([2,2],fill_value=67)
print('arr:',arr)

arr: [[67 67]
 [67 67]]


In [103]:
arr = np.full([3,4],fill_value='NA')
print('arr:',arr)

arr: [['NA' 'NA' 'NA' 'NA']
 ['NA' 'NA' 'NA' 'NA']
 ['NA' 'NA' 'NA' 'NA']]


In [104]:
arr = np.full([4,4],fill_value = 10.1)
print('arr is:',arr)

arr is: [[10.1 10.1 10.1 10.1]
 [10.1 10.1 10.1 10.1]
 [10.1 10.1 10.1 10.1]
 [10.1 10.1 10.1 10.1]]


### np.random()
#### np.random() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval[0.0,1.0].
#### Syntax: numpy.random.random(size=None)
#### Parameters : size : [int or tuple of ints, optional]
#### Output shape.

In [105]:
arr = np.random.rand(10)
print('arr:',arr)

arr: [0.30388717 0.8846453  0.08743744 0.64768312 0.47026942 0.90850775
 0.49167411 0.7105198  0.84978827 0.67652523]


In [106]:
import numpy as np
arr = np.random.rand(2,4)
print('arr:',arr)

arr: [[0.48016031 0.66776859 0.87068637 0.02711626]
 [0.95064067 0.6230918  0.59975531 0.3724916 ]]


In [107]:
arr = np.random.rand(2,3,2)
print('arr:',arr)

arr: [[[0.76569429 0.90966626]
  [0.52413657 0.95052966]
  [0.70889974 0.74448168]]

 [[0.49231077 0.03420354]
  [0.0170826  0.56437731]
  [0.329134   0.35762689]]]


### np.random.randint(value)
### np.random.randint(start,stop)
### np.random.randint(start,stop,size)
    #random int values u needed then use randint
    #Return random integers from `low` (inclusive) to `high` (exclusive).


In [108]:
arr = np.random.randint(6)
print('arr:',arr)

arr: 2


In [109]:
arr = np.random.randint(2,4)
print('arr:',arr)

arr: 2


In [110]:
arr = np.random.randint(4,6,size=10) # 1D Array
print('arr:',arr)
print('dim of array:',arr.ndim)

arr: [5 4 4 4 4 5 4 4 4 4]
dim of array: 1


In [111]:
arr = np.random.randint(1,10,size=(4,4)) # 2D Array
print('arr:',arr)
print('dim of array:',arr.ndim)

arr: [[9 5 3 3]
 [9 6 1 9]
 [6 5 8 4]
 [8 3 7 4]]
dim of array: 2


In [112]:
arr = np.random.randint(1,20,size=(3,2,3)) # 3D Array
print('arr:',arr)
print('dim of arr:',arr.ndim)

arr: [[[ 9 11 11]
  [11 17 15]]

 [[10 11 18]
  [ 6  8  6]]

 [[17 13 15]
  [10 10 17]]]
dim of arr: 3


### np.random.randn(value)
### np.random.randn(start,stop)
### np.random.randn(start,stop,size)
#### The numpy.ndarray.randn() function creates an array of specified shape and fills it with random values as per standard normal disribution.

In [113]:
arr = np.random.randn(10) # 1D Array
print(arr)
print('dim of arr:\n',arr.ndim)

[-1.31342799 -0.59944742 -0.04034326 -0.8988919   1.40076387  0.55072152
 -0.35505435 -0.66624171  0.57639423 -2.58528105]
dim of arr:
 1


In [114]:
arr = np.random.randn(1,10) # 2D Array
print('arr:',arr)
print('dim of arr:\n',arr.ndim)

arr: [[-0.73524661  0.13441463 -0.06711689  2.23268325 -0.79711702  0.4068883
  -0.35482468 -0.09278999 -0.61676804  0.11558806]]
dim of arr:
 2


In [115]:
arr = np.random.randn(2,2,2) # 3D Array
print('arr:',arr)
print('dim of arr:\n',arr.ndim)

arr: [[[-2.42902711 -1.37678681]
  [-0.59325735  0.55792864]]

 [[-0.50528958  1.128243  ]
  [-0.186724   -0.52185934]]]
dim of arr:
 3


### Manipulation with randomly created array

In [116]:
array = np.random.randn(2,2,2)
print('3D Array filled with random values:\n',array * 3) # Multiplying values with 3

3D Array filled with random values:
 [[[ 1.36157042  0.81870217]
  [-3.31200992  2.46616809]]

 [[ 1.30381905 -1.64424436]
  [-0.65336804  1.93547919]]]


In [ ]:
array = np.random.randn(2,2,2) * 3 # Multiplying values with 3
print('3D Array filled with random floats values:\n',array) 

In [ ]:
array = np.random.randn(2,2,2) * 3 + 2 # Multiplying values with 3 and add values 2
print('3D Array filled with random floats values:\n',array) 

### np.random.random(values)
### np.random.random(start,stop)
### np.random.random(start,stop,size)

In [117]:
arr = np.random.random(10) # 1D Array
print('1D Array filled with random floats values:\n',arr)

1D Array filled with random floats values:
 [0.01509531 0.77654168 0.67092344 0.7779956  0.45618217 0.364911
 0.05875023 0.33623356 0.43759593 0.91313775]


In [118]:
arr = np.random.random(size=(1,10)) # 2D Array
print('2D Array filled with random floats values:\n',arr)

2D Array filled with random floats values:
 [[0.70649706 0.86911056 0.57179558 0.86764937 0.8972936  0.70452367
  0.16578616 0.14653955 0.66272228 0.29952883]]


In [119]:
arr = np.random.random(size=(2,3,3)) # 3D Array
print('3D Array filled with random floats values:\n',arr)

3D Array filled with random floats values:
 [[[0.66675261 0.44888468 0.84691036]
  [0.49629865 0.0224623  0.40994711]
  [0.86521936 0.98932429 0.94727296]]

 [[0.6989934  0.91409045 0.31474785]
  [0.94988834 0.4227927  0.45647321]
  [0.10039218 0.03721692 0.70276184]]]


### np.random.random_integers()
#### numpy.random.random_integers() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random integers from low(inclusive) to high(exclusive), i.e. in the interval [ low, high ]
#### Syntax: numpy.radom.random_intergers(low, high=None, size=None)
#### Parameters:
    #low : [int] Lowest(signed) integer to be drawn from the distribution.But,             it works as a highest integer in the sample if high=None.
    #high : [int, optional] Largest(signed) integer to be drawn from the                    distribution.
    #size : [int or tuple of ints, optional] Output shape. If the given shape              is, e.g.,(m,n,k), then m*n*k samples are drawn. Default is None, in            which case a single value is returned. 
    #return: Array of random integers in the interval[low, high] or a single                such random int if size not provided.  

In [120]:
array = np.random.random_integers(low = 0, high = 5, size = 4) # 1D Array
print('1D Array filling random values:\n',array)

1D Array filling random values:
 [3 2 3 2]


C:\Users\DEVKE_~1\AppData\Local\Temp/ipykernel_6940/1914989384.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 5 + 1) instead
  array = np.random.random_integers(low = 0, high = 5, size = 4)


In [121]:
array = np.random.random_integers(low = 0, high = 5, size = (4,4)) # 2D Array
print('2D Array filling random values:\n',array)

2D Array filling random values:
 [[2 1 4 1]
 [5 3 0 2]
 [4 0 4 0]
 [3 2 5 0]]


C:\Users\DEVKE_~1\AppData\Local\Temp/ipykernel_6940/2585859813.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 5 + 1) instead
  array = np.random.random_integers(low = 0, high = 5, size = (4,4))


In [122]:
array = np.random.random_integers(low = 0, high = 5, size = (2,3,2))
print('3D Array filling random values:\n',array)

3D Array filling random values:
 [[[4 0]
  [4 3]
  [2 2]]

 [[1 5]
  [0 5]
  [3 0]]]


C:\Users\DEVKE_~1\AppData\Local\Temp/ipykernel_6940/3230428309.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 5 + 1) instead
  array = np.random.random_integers(low = 0, high = 5, size = (2,3,2))


### np.random.random_sample()
#### numpy.random.random_sample() is one of the function for doing random sampling in numpy It returns an array of specified shape and fills it with randm floats it with random floats in the half-open interval [ 0.0, 1.0).
#### Syntax: numpy.random.random_sample(size = None)

In [130]:
arr = np.random.random_sample()
print('Output random float value:\n',arr)

Output random float value:
 0.14911933636726638


In [129]:
arr = np.random.random_sample(10) # 1D Array
print('Output 1D Array random float value:\n',arr)

Output 1D Array random float value:
 [0.8859242  0.4252503  0.80540984 0.38615435 0.97415977 0.8078116
 0.5262403  0.39513815 0.87919587 0.66348637]


In [128]:
arr = np.random.random_sample(size=(5,15))
print('Output 2D Array random float value:\n',arr)

Output 2D Array random float value:
 [[0.29347715 0.79728354 0.22286117 0.59487485 0.65100221 0.41376438
  0.81929997 0.00241493 0.84304403 0.91671677 0.71563837 0.56649128
  0.80323437 0.31029143 0.06009496]
 [0.74156118 0.98894373 0.15953199 0.05004941 0.1605994  0.06843747
  0.97333625 0.83344015 0.94006086 0.52050864 0.03257288 0.044955
  0.60449746 0.97036778 0.07157347]
 [0.31959172 0.70498125 0.4252257  0.5780254  0.6166321  0.26910394
  0.80998057 0.04506767 0.3553226  0.13529006 0.07063944 0.56585087
  0.23430267 0.57282547 0.39064409]
 [0.51508231 0.19654528 0.08783776 0.52795073 0.10763083 0.68880164
  0.16957442 0.16232746 0.21968412 0.2314187  0.30395005 0.62291736
  0.19473888 0.69942586 0.62807108]
 [0.45061952 0.75582154 0.92237104 0.17385007 0.73105896 0.56091676
  0.99387006 0.50916949 0.85014928 0.42415043 0.40655379 0.37682513
  0.79837297 0.51147922 0.52821023]]


In [133]:
arr = np.random.random_sample(size=(5,10,5))
print('Output 3D Array random float value:\n',arr)

Output 3D Array random float value:
 [[[0.49469455 0.36393908 0.0741625  0.96787471 0.16149034]
  [0.18389321 0.57481283 0.04002987 0.51660528 0.56245118]
  [0.72668309 0.20288244 0.54070682 0.29862387 0.18267972]
  [0.79697196 0.93327618 0.747778   0.25286539 0.20323883]
  [0.08426204 0.9608027  0.5382702  0.90335136 0.90655564]
  [0.41761127 0.91507754 0.1753987  0.44567343 0.14818919]
  [0.53472168 0.28501871 0.39135081 0.7524961  0.77323607]
  [0.6442276  0.6130656  0.54413018 0.71950437 0.86470534]
  [0.62289529 0.95863503 0.3582518  0.9706546  0.49949181]
  [0.25221789 0.30728425 0.96727903 0.52711908 0.89547538]]

 [[0.87748109 0.4091842  0.950972   0.62422833 0.97635059]
  [0.22423752 0.49297231 0.44133856 0.03776265 0.80022312]
  [0.96564355 0.21526722 0.50491415 0.88084762 0.47242118]
  [0.9662515  0.96621775 0.6692485  0.64832175 0.88199771]
  [0.34192984 0.812813   0.81245001 0.46555846 0.77815872]
  [0.67300192 0.46079571 0.42317175 0.00973662 0.4365147 ]
  [0.14431827 0.3

## How To Deal With Data Type?

In [137]:
array = np.arange(4,28).reshape(4,6) # 2D Array
print('2D Array with values:\n',array)

2D Array with values:
 [[ 4  5  6  7  8  9]
 [10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]]


In [138]:
# To check data type of array
print('Data type of array is:',array.dtype)

Data type of array is: int32


In [140]:
array = np.arange(4,28,dtype='float').reshape(4,6) # 2D Array
print('2D Array with values:\n',array)
print('Data type of array is:',array.dtype)

2D Array with values:
 [[ 4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21.]
 [22. 23. 24. 25. 26. 27.]]
Data type of array is: float64


In [141]:
array = np.arange(4,28,dtype='float32').reshape(4,6) # 2D Array
print('2D Array with values:\n',array)
print('Data type of array is:',array.dtype)

2D Array with values:
 [[ 4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21.]
 [22. 23. 24. 25. 26. 27.]]
Data type of array is: float32


In [142]:
array = np.arange(4,28,dtype='float16').reshape(4,6) # 2D Array
print('2D Array with values:\n',array)
print('Data type of array is:',array.dtype)

2D Array with values:
 [[ 4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21.]
 [22. 23. 24. 25. 26. 27.]]
Data type of array is: float16


In [146]:
array = np.arange(4,28,dtype='f2').reshape(4,6) # 'f2' stands for float = 16bits
print('2D Array with values:\n',array)
print('Data type of array is:',array.dtype)

2D Array with values:
 [[ 4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21.]
 [22. 23. 24. 25. 26. 27.]]
Data type of array is: float16


## Change Data Type of given numpy array
### ndarray.astype()
#### In order to change the dtypeof the given array object, we will use numpy.astype() function. The function takes an argument which is the target data type. The function supports all the generic types and built-in types of data.

In [151]:
arr = np.array([10,20,30,40,50])
print('1D Array is:',arr)
print('Data type of 1D Array is:',arr.dtype)
arr = arr.astype('float64') # To change Data type from int32 to float 64
print('1D Array is:',arr)
print('Data type of 1D Array is:',arr.dtype)

1D Array is: [10 20 30 40 50]
Data type of 1D Array is: int32
1D Array is: [10. 20. 30. 40. 50.]
Data type of 1D Array is: float64


In [152]:
arr = np.array([10,20,30,40,50])
print('1D Array is:',arr)
print('Data type of 1D Array is:',arr.dtype)
arr = arr.astype('complex128') # To change Data type from int32 to complex 128
print('1D Array is:',arr)
print('Data type of 1D Array is:',arr.dtype)

1D Array is: [10 20 30 40 50]
Data type of 1D Array is: int32
1D Array is: [10.+0.j 20.+0.j 30.+0.j 40.+0.j 50.+0.j]
Data type of 1D Array is: complex128


In [153]:
arr = np.array([10,20,30,40,50])
print('1D Array is:',arr)
print('Data type of 1D Array is:',arr.dtype)
arr = arr.astype('object') # To change Data type from int32 to object
print('1D Array is:',arr)
print('Data type of 1D Array is:',arr.dtype)

1D Array is: [10 20 30 40 50]
Data type of 1D Array is: int32
1D Array is: [10 20 30 40 50]
Data type of 1D Array is: object


## How to convert NumPy array to List?

### ndarray.tolist()
#### We can convert the NumPy array to the list by tolist() method, we can have a list of data element which is converted from an array using this method.
#### Syntax : ndarray.tolist()

In [160]:
arr = np.arange(1,17).reshape(4,4)
print('2D Array is:\n',arr)
print('Type of 2D Array is:',type(arr))
print('Data type of 2D Array is:',arr.dtype)

2D Array is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
<class 'numpy.ndarray'>
Data type of 2D Array is: int32


In [163]:
list = arr.tolist()
print('List:',list)
print('Type of List is:',type(list))

List: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
Type of List is: <class 'list'>


## Copying arrays
### numpy.ndarray.copy()
#### It returns a copy of the array.
#### Syntax: numpy.ndarray.copy(order='C')
#### Parameters:
#### Order : Controls the memory layout of the copy. 'C' means C-order, 'F' means F-order, 'A' means 'F' if a is Fortran contiguous, 'C' otherwise. 'K' means match the layout of a as closely as possible.

In [164]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [165]:
print('Id of arr is:',id(arr))

Id of arr is: 2232189215920


### Shallow Copy:

In [168]:
arr1 = arr.copy() # Shallow copy
print('copying arr to arr1:\n',arr1)
print('Id of arr1 is:',id(arr1))

copying arr to arr1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Id of arr1 is: 2232189214864


### Deep Copy

In [169]:
arr1 = arr 
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [170]:
print('Id of arr is:',id(arr))
print('Id of arr1 is:',id(arr1))

Id of arr is: 2232189218608
Id of arr1 is: 2232189218608


## Statistics on NumPy Array / Measures of Central Tendency

### mean() : Takes a NumPy array as an argument and returns the arithmetic mean of the data.


In [173]:
# np.mean(array)

### median() : Takes a NumPy array as an argument and returns the median of the data.

In [174]:
# np.median(array)

### ptp() : It takes a NumPy array as an argumnet and returns the range of the data.

In [175]:
# np.ptp(array)

### var() : It takes a NumPy array as an argument and returns the variance of the data.

In [176]:
# np.var(array)

### std() : It takes a NumPy array as an argumnet and returns the standard variation of the data.

In [177]:
# np.std(array)

### sum() : It takes a NumPy array as an argument and returns the sum of the array elements.

In [178]:
# np.sum(array)

### min() : It takes a NumPy array as an argument and returns the minimum value in the array.

In [179]:
# np.min(array)

### max() : It takes a NumPy array as an argument and returns the maximum value in the array.

In [180]:
# np.max(array)

In [6]:
import numpy as np
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
print('Maximum value of 2D Array is:\n',np.max(arr))
print('Minimum value of 2D Array is:\n',np.min(arr))
print('Mean value of 2D Array is:\n',np.mean(arr))
print('Median value of 2D Array is:\n',np.median(arr))
print('Range of 2D Array is:\n',np.ptp(arr))
print('Standard Deviation of 2D Array is:\n',np.std(arr))
print('Variance of 2D Array is:\n',np.var(arr))
print('Sum of 2D Array is:\n',np.sum(arr))
print('Cummulative sum of 2D Array is:\n',np.cumsum(arr))
print('Cummulative product od 2D Array is:\n',np.cumprod(arr))

Maximum value of 2D Array is:
 9
Minimum value of 2D Array is:
 1
Mean value of 2D Array is:
 5.0
Median value of 2D Array is:
 5.0
Range of 2D Array is:
 8
Standard Deviation of 2D Array is:
 2.581988897471611
Variance of 2D Array is:
 6.666666666666667
Sum of 2D Array is:
 45
Cummulative sum of 2D Array is:
 [ 1  3  6 10 15 21 28 36 45]
Cummulative product od 2D Array is:
 [     1      2      6     24    120    720   5040  40320 362880]


In [21]:
arr1 = np.arange(1,24)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [19]:
print('Maximum value of 1D Array is:\n',arr1.max())
print('Minimum value of 1D Array is:\n',arr1.min())
print('Mean value of 1D Array is:\n',arr1.mean())
#print('Median value of 1D Array is:\n',arr1.median())
print('Range of 1D Array is:\n',arr1.ptp())
print('Standard Deviation of 1D Array is:\n',arr1.std())
print('Variance of 1D Array is:\n',arr1.var())
print('Sum of 1D Array is:\n',arr1.sum())
print('Cummulative sum of 1D Array is:\n',arr1.cumsum())
print('Cummulative product od 1D Array is:\n',arr1.cumprod())

Maximum value of 1D Array is:
 23
Minimum value of 1D Array is:
 1
Mean value of 1D Array is:
 12.0
Range of 1D Array is:
 22
Standard Deviation of 1D Array is:
 6.6332495807108
Variance of 1D Array is:
 44.0
Sum of 1D Array is:
 276
Cummulative sum of 1D Array is:
 [  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210 231 253 276]
Cummulative product od 1D Array is:
 [          1           2           6          24         120         720
        5040       40320      362880     3628800    39916800   479001600
  1932053504  1278945280  2004310016  2004189184  -288522240  -898433024
   109641728 -2102132736 -1195114496  -522715136   862453760]


## NumPy Sorting Operation on Arrays

### Sorting Arrays

#### Sorting means putting elements in an ordered sequence.
#### Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
#### The NumPy ndarray object has a function called 'sort()' that will sort a specified array.
#### Note: This method returns a copy of the array leaving the original array unchanged.

In [23]:
arr = np.array([3,2,0,1])
print('Sorting the 1D Array is:',np.sort(arr))

Sorting the 1D Array is: [0 1 2 3]


#### You can also sort arrays of strings or any other data type.

In [29]:
arr = np.array(['banana','cherry','apple'])
print('Sorting the 1D Array is:\n',np.sort(arr))

Sorting the 1D Array is:
 ['apple' 'banana' 'cherry']


#### Sort a boolean array

In [26]:
arr = np.array([True,False,True])
print('Sorting the 1D Array is:\n',np.sort(arr))

Sorting the 1D Array is: [False  True  True]


### Sorting a 2D Arrays

In [3]:
import numpy as np
arr = np.arange(1,25).reshape(6,4)
print('2D Array fill with values is:\n',arr)

2D Array fill with values is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


### Row-wise find out values use axis=1

In [9]:
print('Row-wise Maximum value of 2D Array is:\n',np.max(arr,axis=1))
print('Row-wise Minimum value of 2D Array is:\n',np.min(arr,axis=1))
print('Row-wise Mean value of 2D Array is:\n',np.mean(arr,axis=1))
print('Row-wise median value of 2D Array is:\n',np.median(arr,axis=1))
print('Row-wise variance value of 2D Array is:\n',np.var(arr,axis=1))
print('Row-wise standard deviation value of 2D Array is:\n',np.std(arr,axis=1))
print('Row-wise range of 2D Array is:\n',np.ptp(arr,axis=1))
print('Row-wise sum of values of 2D Array is:\n',np.sum(arr,axis=1))
print('Row-wise cummulative sum of 2D Array is:\n',np.cumsum(arr,axis=1))
print('Row-wise cummulative product of 2D Array is:\n',np.cumprod(arr,axis=1))
print('Row-wise sort values of 2D Array is:\n',np.sort(arr,axis=1))

Row-wise Maximum value of 2D Array is:
 [ 4  8 12 16 20 24]
Row-wise Minimum value of 2D Array is:
 [ 1  5  9 13 17 21]
Row-wise Mean value of 2D Array is:
 [ 2.5  6.5 10.5 14.5 18.5 22.5]
Row-wise median value of 2D Array is:
 [ 2.5  6.5 10.5 14.5 18.5 22.5]
Row-wise variance value of 2D Array is:
 [1.25 1.25 1.25 1.25 1.25 1.25]
Row-wise standard deviation value of 2D Array is:
 [1.11803399 1.11803399 1.11803399 1.11803399 1.11803399 1.11803399]
Row-wise range of 2D Array is:
 [3 3 3 3 3 3]
Row-wise sum of values of 2D Array is:
 [10 26 42 58 74 90]
Row-wise cummulative sum of 2D Array is:
 [[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]
 [13 27 42 58]
 [17 35 54 74]
 [21 43 66 90]]
Row-wise cummulative product of 2D Array is:
 [[     1      2      6     24]
 [     5     30    210   1680]
 [     9     90    990  11880]
 [    13    182   2730  43680]
 [    17    306   5814 116280]
 [    21    462  10626 255024]]
Row-wise sort values of 2D Array is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 

### Column-wise find out values use axis=0

In [10]:
print('Column-wise Maximum value of 2D Array is:\n',np.max(arr,axis=0))
print('Column-wise Minimum value of 2D Array is:\n',np.min(arr,axis=0))
print('Column-wise Mean value of 2D Array is:\n',np.mean(arr,axis=0))
print('Column-wise median value of 2D Array is:\n',np.median(arr,axis=0))
print('Column-wise variance value of 2D Array is:\n',np.var(arr,axis=0))
print('Column-wise standard deviation value of 2D Array is:\n',np.std(arr,axis=0))
print('Column-wise range of 2D Array is:\n',np.ptp(arr,axis=0))
print('Column-wise sum of values of 2D Array is:\n',np.sum(arr,axis=0))
print('Column-wise cummulative sum of 2D Arrays is:\n',np.cumsum(arr,axis=0))
print('Column-wise cummulative product of 2D Arrays is:\n',np.cumprod(arr,axis=0))
print('Column-wise sort values of 2D Array is:\n',np.sort(arr,axis=0))

Column-wise Maximum value of 2D Array is:
 [21 22 23 24]
Column-wise Minimum value of 2D Array is:
 [1 2 3 4]
Column-wise Mean value of 2D Array is:
 [11. 12. 13. 14.]
Column-wise median value of 2D Array is:
 [11. 12. 13. 14.]
Column-wise variance value of 2D Array is:
 [46.66666667 46.66666667 46.66666667 46.66666667]
Column-wise standard deviation value of 2D Array is:
 [6.83130051 6.83130051 6.83130051 6.83130051]
Column-wise range of 2D Array is:
 [20 20 20 20]
Column-wise sum of values of 2D Array is:
 [66 72 78 84]
Column-wise cummulative sum of 2D Arrays is:
 [[ 1  2  3  4]
 [ 6  8 10 12]
 [15 18 21 24]
 [28 32 36 40]
 [45 50 55 60]
 [66 72 78 84]]
Column-wise cummulative product of 2D Arrays is:
 [[      1       2       3       4]
 [      5      12      21      32]
 [     45     120     231     384]
 [    585    1680    3465    6144]
 [   9945   30240   65835  122880]
 [ 208845  665280 1514205 2949120]]
Column-wise sort values of 2D Array is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 

## To check the signature of any function of numpy
### Different ways are as follows:
    # np.linspace#shift tab
    # np.linspace?
    # help(np.linspace)
    # np.info(np.linspace)

In [11]:
np.linspace?

## NumPy Array Shape manipulation:

In [20]:
arr = np.arange(1,29)
print('1D Array is:\n',arr)
print('Size of 1D Array is:',arr.size)
print('Dimension of Array is:',arr.ndim)

1D Array is:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28]
Size of 1D Array is: 28
Dimension of Array is: 1


## reshape()
### reshape does not change original object
### it just gives reflection
### temp change
### reshape is not inplace

In [21]:
#1D: 28
#2D(rows,column): (4,7) (7,4) (2,14) (14,2) (1,28) (28,1) 
#3D(block,row,column): (2,2,7) (7,4,4) (2,14,1) (1,1,28)

In [24]:
arr = np.arange(1,29).reshape(28)
print('1D Array is:\n',arr)

1D Array is:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28]


In [25]:
arr = np.arange(1,29).reshape(4,7)
print('2D Array is:\n',arr)

2D Array is:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]


In [30]:
arr = np.arange(1,29).reshape(4,-1)
print('2D Array is:\n',arr)

2D Array is:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]


In [31]:
arr = np.arange(1,29).reshape(-1,7)
print('2D Array is:\n',arr)

2D Array is:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]


In [27]:
arr = np.arange(1,29).reshape(2,7,2)
print('3D Array is:\n',arr)

3D Array is:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]
  [13 14]]

 [[15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]
  [25 26]
  [27 28]]]


In [32]:
arr = np.arange(1,29).reshape(2,7,-1)
print('3D Array is:\n',arr)

3D Array is:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]
  [13 14]]

 [[15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]
  [25 26]
  [27 28]]]


In [33]:
arr = np.arange(1,29).reshape(-1,7,2)
print('3D Array is:\n',arr)

3D Array is:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]
  [13 14]]

 [[15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]
  [25 26]
  [27 28]]]


In [34]:
arr = np.arange(1,29).reshape(2,-1,2)
print('3D Array is:\n',arr)

3D Array is:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]
  [13 14]]

 [[15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]
  [25 26]
  [27 28]]]


## How to do reshape as inplace
### resize()
### resize  change original object
### it not gives reflection
### permanant change
### resize is  inplace

In [42]:
a = np.arange(1,29)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [44]:
a.size

28

In [45]:
a.resize(28) # 1D Array
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [46]:
a.resize(7,4) # 2D Array
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

In [47]:
a.resize(7,2,2) # 3D Array
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28]]])

### make the rows as column and column as rows
### a.T #transpose

In [51]:
a = np.arange(1,29)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [56]:
a.resize(7,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

In [57]:
a.T

array([[ 1,  5,  9, 13, 17, 21, 25],
       [ 2,  6, 10, 14, 18, 22, 26],
       [ 3,  7, 11, 15, 19, 23, 27],
       [ 4,  8, 12, 16, 20, 24, 28]])

In [58]:
np.transpose(a)

array([[ 1,  5,  9, 13, 17, 21, 25],
       [ 2,  6, 10, 14, 18, 22, 26],
       [ 3,  7, 11, 15, 19, 23, 27],
       [ 4,  8, 12, 16, 20, 24, 28]])

In [59]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

In [61]:
a.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]])

### ndarray.shape = ()

In [5]:
import numpy as np
a = np.arange(2,30)
print('Array a is:\n',a)

Array a is:
 [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29]


In [7]:
a.shape = (4,7) #2D Array

In [8]:
a

array([[ 2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29]])

In [10]:
print('Dimension of Array a is:\n',a.ndim)

Dimension of Array a is:
 2


In [11]:
a.shape = (7,2,2) # 3D Array
a

array([[[ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21]],

       [[22, 23],
        [24, 25]],

       [[26, 27],
        [28, 29]]])

In [12]:
print('Dimension of Array a is:\n',a.ndim)

Dimension of Array a is:
 3


In [19]:
a.shape = (28) # 1D Array
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
print('Dimension of Array a is:\n',a.ndim)

Dimension of Array a is:
 1


### Adding Elements to NumPy Array using numpy.add(arr1,arr2)
### numpy.add()
#### numpy.add() function is used when we want to compute the addition of two array. It add argumnets element-wise. If shape of two arrays are not same, that is arr1.shape ! = arr.shape, they must be broadcastable to common shape(which may be the shape of one or the other.)
#### Syntax: numpy.add(arr1,arr2)

In [21]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print('Array1 is:\n',arr1)
print('Array2 is:\n',arr2)
arr3 = np.add(arr1,arr2)
print('Addition of Array1 & Array2 is:\n',arr3)

Array1 is:
 [1 2 3 4]
Array2 is:
 [5 6 7 8]
Addition of Array1 & Array2 is:
 [ 6  8 10 12]


In [2]:
import numpy as np
arr1 = np.array([[2,-7,5],[-6,2,0]])
arr2 = np.array([[5,8,-5],[3,6,9]])
print('Array1 is:\n',arr1)
print('Array2 is:\n',arr2)
arr3 = np.add(arr1,arr2)
print('Addition of Array1 & Array2 is:\n',arr3)

Array1 is:
 [[ 2 -7  5]
 [-6  2  0]]
Array2 is:
 [[ 5  8 -5]
 [ 3  6  9]]
Addition of Array1 & Array2 is:
 [[ 7  1  0]
 [-3  8  9]]


### Add Elements to NumPy Array using numpy.append()
#### NumPy module in python, provides a function to numpy.append() to add an element in a numpy array. 
#### It doesn't modifies the existing array, but returns a copy of the passed array with given value added to it.

In [3]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([100,200,300,400,500,600])
print('Array1 is:\n',arr1)
print('Array2 is:\n',arr2)
arr3 = np.append(arr1,arr2)
print('Array3 is:\n',arr3)

Array1 is:
 [10 20 30 40 50 60]
Array2 is:
 [100 200 300 400 500 600]
Array3 is:
 [ 10  20  30  40  50  60 100 200 300 400 500 600]


In [4]:
print('Add Elements to Array1:\n',np.append(arr1,450))

Add Elements to Array1:
 [ 10  20  30  40  50  60 450]


In [5]:
print('Add Elements to Array2:\n',np.append(arr2,555))

Add Elements to Array2:
 [100 200 300 400 500 600 555]


#### Row-wise Append

In [5]:
import numpy as np
arr1 = np.array([5,10,15,20,25])
arr2 = np.array([9,18,27,36,45])
print('Array1 is:\n',arr1)
print('Array2 is:\n',arr2)
arr3 = np.append(arr1,arr2,axis=0)
print("Append elements in 1D Array3 Column-wise:\n",arr3)

Array1 is:
 [ 5 10 15 20 25]
Array2 is:
 [ 9 18 27 36 45]
Append elements in 1D Array3 Column-wise:
 [ 5 10 15 20 25  9 18 27 36 45]


In [6]:
arr1 = np.array([[10,20,30],[150,250,350]])
arr2 = np.array([[5,10,15],[4,8,12]])
print('Array1 is:\n',arr1)
print('Array2 is:\n',arr2)
arr3 = np.append(arr1,arr2,axis=1)
print('Append Elements in 2D Array3 Row-wise:\n',arr3)

Array1 is:
 [[ 10  20  30]
 [150 250 350]]
Array2 is:
 [[ 5 10 15]
 [ 4  8 12]]
Append Elements in 2D Array3 Row-wise:
 [[ 10  20  30   5  10  15]
 [150 250 350   4   8  12]]


In [8]:
arr1 = np.array([[10,20,30],[150,250,350]])
arr2 = np.array([[5,10,15],[4,8,12]])
print('Array1 is:\n',arr1)
print('Array2 is:\n',arr2)
arr3 = np.append(arr1,arr2,axis=0)
print('Append Elements in 2D Array3 Column-wise:\n',arr3)

Array1 is:
 [[ 10  20  30]
 [150 250 350]]
Array2 is:
 [[ 5 10 15]
 [ 4  8 12]]
Append Elements in 2D Array3 Column-wise:
 [[ 10  20  30]
 [150 250 350]
 [  5  10  15]
 [  4   8  12]]


### numpy.conacatenate() function

#### Join a sequence of arrays along an existing axis. here axis=0 hence will concate columnwise.

In [12]:
arr1

array([[ 10,  20,  30],
       [150, 250, 350]])

In [13]:
arr2

array([[ 5, 10, 15],
       [ 4,  8, 12]])

In [15]:
arr3 = np.concatenate((arr1,arr2))
print('Array3 is:\n',arr3)

Array3 is:
 [[ 10  20  30]
 [150 250 350]
 [  5  10  15]
 [  4   8  12]]


#### Row-wise concatenate

In [25]:
np.concatenate((arr1,arr2),axis=0)

array([10, 20, 30, 25, 50, 75])

## Conditional Selection

In [32]:
a = np.arange(2,30).reshape(7,4)
print(a)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]


In [39]:
# select a number greater than 15
a > 15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#### bool array acts as an index

In [40]:
print(a[a>15])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [42]:
a[np.array(a>15)]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### array supports bool indexing

## np.where()

#### Python NumPy module contains many built-in functions to create and manipulate array elments altogether.
#### The numpy.where() function is udes to return the array elements based on certain conditions.
#### Syntax: numpy.where(condition,a,b)
     #condition: The manipulation condition to be applied on the array needs to       be mentioned.
     # a: If the conditon is met i.e.the condition turns out to be True, then          the function yields a.
     #b: If the condition is not met,this value is returned by the function.

In [2]:
import numpy as np
arr = np.array([[10,20,30],[40,50,60]])
print('Array is:\n',arr)
print('Array gives Boolean output:\n',np.where(arr<20,True,False))

Array is:
 [[10 20 30]
 [40 50 60]]
Array gives Boolean output:
 [[ True False False]
 [False False False]]


    # In the above example, for all the array elements whose data values<20, those data values are replaced by True.And, all the array elements whose data values is >20 i.e.the values are replaced by False.

In [7]:
import numpy as np
arr = np.array([[10,20,30],[40,50,60]])
print('Array is:\n',arr)
arr1 = np.where(arr<20)
print('Array1 Elements less than 20:\n',arr[arr1])

Array is:
 [[10 20 30]
 [40 50 60]]
Array1 Elements less than 20:
 [10]


### numpy.where() function with Multiple conditions
    #Multiple condition can be applied along with the numpy.where() function to manipulate the array elements against multiple conditions.
    #Syntax: 
            numpy.where((condition1) & (condition2))
                                    OR
            numpy.where((condition1) | (condition2))
            
                                    

In [8]:
import numpy as np
data = np.array([[10,20,30],[40,50,60],[0,1,2]])
print('Data of Array:\n',data)
data1 = np.where((data!=20)&(data<40)) # Elements whose are less than 40 and not equal to 20
print(data1)
print()
print(data[data1])

Data of Array:
 [[10 20 30]
 [40 50 60]
 [ 0  1  2]]
(array([0, 0, 2, 2, 2], dtype=int64), array([0, 2, 0, 1, 2], dtype=int64))

[10 30  0  1  2]


In [11]:
data = np.array([[10,20,30],[40,50,60],[0,1,2]])
print('Data Array is:\n',data)
data1 = np.where((data<20)|(data>40)) #Elements whose less than 20 and greater than 40
print(data1)
print()
print(data[data1])

Data Array is:
 [[10 20 30]
 [40 50 60]
 [ 0  1  2]]
(array([0, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))

[10 50 60  0  1  2]


### Replacing the array values using numpy.where() function
    #Using numpy.where() function on fullfillment of certain condition.
    #Syntax: numpy.where(condition,element1,element2)

In [14]:
data = np.random.randn(2,3)
print('Data before manipulation:\n',data)
print()
data1 = np.where((data>0),data,0)
print('Data after manipulation:\n',data1)

Data before manipulation:
 [[ 0.35655235  0.84917988 -0.66932854]
 [ 0.74400938 -0.635384   -0.57455891]]

Data after manipulation:
 [[0.35655235 0.84917988 0.        ]
 [0.74400938 0.         0.        ]]


In [16]:
a = np.arange(1,25).reshape(4,6)
print('Array of a is:\n',a)
b = np.where(a>15)
print('Elements greter than 15 is:\n',b)
print('Elements greter than 15 is:\n',a[b])
print()
np.where(a>15)

Array of a is:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Elements greter than 15 is:
 (array([2, 2, 2, 3, 3, 3, 3, 3, 3], dtype=int64), array([3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int64))
Elements greter than 15 is:
 [16 17 18 19 20 21 22 23 24]



(array([2, 2, 2, 3, 3, 3, 3, 3, 3], dtype=int64),
 array([3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int64))

In [22]:
a = np.arange(1,25).reshape(6,4)
print('Array of a is:\n',a)
print()

Array of a is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]




In [23]:
np.where(a<15)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1], dtype=int64))

In [21]:
b = np.where(a<15)
print('Elements less than 15 is:\n',a[b])

Elements less than 15 is:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [24]:
np.where(a<15,a,-a)

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14, -15, -16],
       [-17, -18, -19, -20],
       [-21, -22, -23, -24]])

In [26]:
b = np.where(a<15,a,-a)
print('Elements are less than 15 & replace by -:\n',b)

Elements are less than 15 & replace by -:
 [[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14 -15 -16]
 [-17 -18 -19 -20]
 [-21 -22 -23 -24]]


In [27]:
np.where(a<15,a,0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [28]:
b = np.where(a<15,a,0)
print('Elements are less than 15 and replace by 0:\n',b)

Elements are less than 15 and replace by 0:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]


In [30]:
salary = np.array([25,65,75,20,15])
print('Array of Salary is:\n',salary)
new_salary = np.where(salary<30,salary+1,salary)*1000
#where salary is <30 give 1k bonus
#where salary is not <30 keep as it is
print('New_salary:\n',new_salary)

Array of Salary is:
 [25 65 75 20 15]
New_salary:
 [26000 65000 75000 21000 16000]


In [31]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [33]:
np.where(a%2==0)

(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5], dtype=int64),
 array([1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3], dtype=int64))

In [35]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

## Scalar math

In [36]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [39]:
a+10 # Added 10 value in array a elements

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34]])

In [38]:
a # a is unchanged

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [43]:
a+=10 # a is changed

In [41]:
a

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34]])

In [42]:
a

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34]])

In [44]:
a**2

array([[ 441,  484,  529,  576],
       [ 625,  676,  729,  784],
       [ 841,  900,  961, 1024],
       [1089, 1156, 1225, 1296],
       [1369, 1444, 1521, 1600],
       [1681, 1764, 1849, 1936]], dtype=int32)

In [47]:
a**=2

In [48]:
a

array([[ 194481,  234256,  279841,  331776],
       [ 390625,  456976,  531441,  614656],
       [ 707281,  810000,  923521, 1048576],
       [1185921, 1336336, 1500625, 1679616],
       [1874161, 2085136, 2313441, 2560000],
       [2825761, 3111696, 3418801, 3748096]])

## Vector Math

In [50]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,1],[2,1]])
print('x Array is:',x)
print('y Array is:',y)
z = x + y # Elementwise addition
print('Addition of x & y array is:\n',z)

x Array is: [[1 2]
 [3 4]]
y Array is: [[1 1]
 [2 1]]
Addition of x & y array is:
 [[2 3]
 [5 5]]


In [51]:
z = x & y

In [52]:
z

array([[1, 0],
       [2, 0]], dtype=int32)

In [53]:
12 and 40

40

In [54]:
x + y

array([[2, 3],
       [5, 5]])

In [55]:
np.add(x,y)

array([[2, 3],
       [5, 5]])

In [57]:
np.subtract(x,y)

array([[0, 1],
       [1, 3]])

In [59]:
np.multiply(x,y)

array([[1, 2],
       [6, 4]])

In [60]:
np.divide(x,y)

array([[1. , 2. ],
       [1.5, 4. ]])

In [61]:
np.power(x,y)

array([[1, 2],
       [9, 4]], dtype=int32)

In [62]:
a

array([[ 194481,  234256,  279841,  331776],
       [ 390625,  456976,  531441,  614656],
       [ 707281,  810000,  923521, 1048576],
       [1185921, 1336336, 1500625, 1679616],
       [1874161, 2085136, 2313441, 2560000],
       [2825761, 3111696, 3418801, 3748096]])

In [64]:
~a # provide negative sign

array([[ -194482,  -234257,  -279842,  -331777],
       [ -390626,  -456977,  -531442,  -614657],
       [ -707282,  -810001,  -923522, -1048577],
       [-1185922, -1336337, -1500626, -1679617],
       [-1874162, -2085137, -2313442, -2560001],
       [-2825762, -3111697, -3418802, -3748097]], dtype=int32)

In [65]:
np.sin(a)

array([[-0.64938811,  0.00219242,  0.47308474, -0.96795625],
       [-0.58958695, -0.06734017,  0.23581702, -0.25295416],
       [ 0.99409467, -0.02452983, -0.41323633,  0.33049314],
       [ 0.92807   ,  0.12513593, -0.65432095,  0.92720115],
       [-0.07971149, -0.95377357, -0.42976307, -0.82465462],
       [-0.8728142 , -0.95144548,  0.47401299,  0.03507158]])

In [66]:
np.log(a)

array([[12.17808975, 12.36416981, 12.54197686, 12.71221532],
       [12.8755033 , 13.03238615, 13.18334746, 13.32881804],
       [13.46918332, 13.60478953, 13.73594882, 13.86294361],
       [13.98603025, 14.1054421 , 14.22139225, 14.33407575],
       [14.44367165, 14.55034464, 14.65424658, 14.75551782],
       [14.85428827, 14.95067847, 15.04480046, 15.13675854]])

In [67]:
x

array([[1, 2],
       [3, 4]])

In [68]:
np.add(x,10)

array([[11, 12],
       [13, 14]])

## How to Delete Element?

### numpy.ravel()
#### The numpy.ravel() functions returns contiguous faltterned(1D array with all the input-array elements and with the same type as it). A copy is made only if needed.
#### Syntax: numpy.ravel(array,order = 'C')
#### numpy.ravel() is converted multidimensional array to 1D array.

In [72]:
import numpy as np
array = np.arange(15).reshape(3,5)
print('Original Array:\n',array)
print('Dimension of Original Array is:\n',array.ndim)
print('\nravel():',array.ravel())
print('Dimension of ravel Array is:\n',array.ravel().ndim)

Original Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Dimension of Original Array is:
 2

ravel(): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Dimension of ravel Array is:
 1


In [75]:
array # array is not changed

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
print('\nreshape_array is:\n',array.reshape(-1))


reshape_array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### numpy.delete()
#### The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.
#### Syntax: np.delete(array,object,axis=None)

In [77]:
a

array([[ 194481,  234256,  279841,  331776],
       [ 390625,  456976,  531441,  614656],
       [ 707281,  810000,  923521, 1048576],
       [1185921, 1336336, 1500625, 1679616],
       [1874161, 2085136, 2313441, 2560000],
       [2825761, 3111696, 3418801, 3748096]])

In [78]:
np.delete(a,2)

array([ 194481,  234256,  331776,  390625,  456976,  531441,  614656,
        707281,  810000,  923521, 1048576, 1185921, 1336336, 1500625,
       1679616, 1874161, 2085136, 2313441, 2560000, 2825761, 3111696,
       3418801, 3748096])

### Delete rowwise

In [79]:
a

array([[ 194481,  234256,  279841,  331776],
       [ 390625,  456976,  531441,  614656],
       [ 707281,  810000,  923521, 1048576],
       [1185921, 1336336, 1500625, 1679616],
       [1874161, 2085136, 2313441, 2560000],
       [2825761, 3111696, 3418801, 3748096]])

In [80]:
a[0] # Delete row

array([194481, 234256, 279841, 331776])

In [88]:
np.delete(a,0,axis=0)#axis=1 means row

array([[ 390625,  456976,  531441,  614656],
       [ 707281,  810000,  923521, 1048576],
       [1185921, 1336336, 1500625, 1679616],
       [1874161, 2085136, 2313441, 2560000],
       [2825761, 3111696, 3418801, 3748096]])

### Delete Columnwise 

In [82]:
a

array([[ 194481,  234256,  279841,  331776],
       [ 390625,  456976,  531441,  614656],
       [ 707281,  810000,  923521, 1048576],
       [1185921, 1336336, 1500625, 1679616],
       [1874161, 2085136, 2313441, 2560000],
       [2825761, 3111696, 3418801, 3748096]])

In [90]:
a[:,1]

array([ 234256,  456976,  810000, 1336336, 2085136, 3111696])

In [89]:
np.delete(a,1,axis=1) # Delete column no.2 as index[1]

array([[ 194481,  279841,  331776],
       [ 390625,  531441,  614656],
       [ 707281,  923521, 1048576],
       [1185921, 1500625, 1679616],
       [1874161, 2313441, 2560000],
       [2825761, 3418801, 3748096]])

### Spliting NumPy Arrays
#### Spliting reverse operation of joining.
#### Joining merges multiple arrays into one and splitting breaks one array into multiple array.
#### Syntax: np.split()

In [91]:
a

array([[ 194481,  234256,  279841,  331776],
       [ 390625,  456976,  531441,  614656],
       [ 707281,  810000,  923521, 1048576],
       [1185921, 1336336, 1500625, 1679616],
       [1874161, 2085136, 2313441, 2560000],
       [2825761, 3111696, 3418801, 3748096]])

In [95]:
a.shape

(6, 4)

In [93]:
np.split(a,2) # split array into multiple sub-array

[array([[ 194481,  234256,  279841,  331776],
        [ 390625,  456976,  531441,  614656],
        [ 707281,  810000,  923521, 1048576]]),
 array([[1185921, 1336336, 1500625, 1679616],
        [1874161, 2085136, 2313441, 2560000],
        [2825761, 3111696, 3418801, 3748096]])]

In [100]:
np.split(a,3)

[array([[194481, 234256, 279841, 331776],
        [390625, 456976, 531441, 614656]]),
 array([[ 707281,  810000,  923521, 1048576],
        [1185921, 1336336, 1500625, 1679616]]),
 array([[1874161, 2085136, 2313441, 2560000],
        [2825761, 3111696, 3418801, 3748096]])]

In [101]:
np.split(a,3,axis=0) # Row-wise split

[array([[194481, 234256, 279841, 331776],
        [390625, 456976, 531441, 614656]]),
 array([[ 707281,  810000,  923521, 1048576],
        [1185921, 1336336, 1500625, 1679616]]),
 array([[1874161, 2085136, 2313441, 2560000],
        [2825761, 3111696, 3418801, 3748096]])]

In [105]:
np.split(a,2,axis=1) # column-wise split

[array([[ 194481,  234256],
        [ 390625,  456976],
        [ 707281,  810000],
        [1185921, 1336336],
        [1874161, 2085136],
        [2825761, 3111696]]),
 array([[ 279841,  331776],
        [ 531441,  614656],
        [ 923521, 1048576],
        [1500625, 1679616],
        [2313441, 2560000],
        [3418801, 3748096]])]

In [106]:
a

array([[ 194481,  234256,  279841,  331776],
       [ 390625,  456976,  531441,  614656],
       [ 707281,  810000,  923521, 1048576],
       [1185921, 1336336, 1500625, 1679616],
       [1874161, 2085136, 2313441, 2560000],
       [2825761, 3111696, 3418801, 3748096]])

In [107]:
np.vsplit(a,2) # Row-wise split

[array([[ 194481,  234256,  279841,  331776],
        [ 390625,  456976,  531441,  614656],
        [ 707281,  810000,  923521, 1048576]]),
 array([[1185921, 1336336, 1500625, 1679616],
        [1874161, 2085136, 2313441, 2560000],
        [2825761, 3111696, 3418801, 3748096]])]

In [108]:
a

array([[ 194481,  234256,  279841,  331776],
       [ 390625,  456976,  531441,  614656],
       [ 707281,  810000,  923521, 1048576],
       [1185921, 1336336, 1500625, 1679616],
       [1874161, 2085136, 2313441, 2560000],
       [2825761, 3111696, 3418801, 3748096]])

In [110]:
np.hsplit(a,2) # column-wise split

[array([[ 194481,  234256],
        [ 390625,  456976],
        [ 707281,  810000],
        [1185921, 1336336],
        [1874161, 2085136],
        [2825761, 3111696]]),
 array([[ 279841,  331776],
        [ 531441,  614656],
        [ 923521, 1048576],
        [1500625, 1679616],
        [2313441, 2560000],
        [3418801, 3748096]])]